name: Data PR

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📌 Setup runtime
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: 📌 Checkout repo
      uses: actions/checkout@v2
    - name: 📌 Run script
      run: echo "This workflow was triggered by a webhook!"